project_name: pgbouncer_exporter
release:
  github:
    owner: jbub
    name: pgbouncer_exporter
builds:
  - main: main.go
    binary: pgbouncer_exporter
    ldflags: |
      -s
      -w
      -X github.com/prometheus/common/version.Version={{ .Version }}
      -X github.com/prometheus/common/version.Revision={{ .Commit }}
      -X github.com/prometheus/common/version.BuildDate={{ .Date }}
      -extldflags '-static'
    flags: -tags netgo
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - id: release
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
dockers:
  - skip_push: auto
    goos: linux
    goarch: amd64
    ids:
      - pgbouncer_exporter
    image_templates:
      - "jbub/pgbouncer_exporter:latest"
      - "jbub/pgbouncer_exporter:{{ .Tag }}"
